### ISSUE TITLE
parseToken bug

### ISSUE THREAD

**Issue by yuanzhihai** [edenleung/jwt-auth#1]
JwtAuth\Jwt::parseToken(): Argument #1 ($token) must be of type string,

**Comment by edenleung** [comment]
是这里的事件触发有问题吗？可以提供下trace不

 `$this->event->verify($this->parseToken($token));`

**Comment by yuanzhihai** [comment]
> 是这里的事件触发有问题吗？可以提供下trace不
> 
> `$this->event->verify($this->parseToken($token));`
```
/**
     * 生成 Token
     * @param $id  唯一标识
     * @param $cliams 附带参数
     *
     * @return Token
     */
    public function token($id, $cliams = [])
    {

        $token = $this->jwt->make($id, $cliams);

        $this->event->login($this->parseToken($token));

        return $token;
    }
```
make 返回的是对象，parseToken 参数需要string

**Comment by edenleung** [comment]
那login事件这块不用parseToken了
